baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Thinking Brain'

theme="gohugo-theme-ananke"

enableRobotsTXT = true
[pagination]
  pagerSize = 5


# Menu (Navigation Bar)
[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 2

  [[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 3

  [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 4

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5
